import PDFDocument from 'pdfkit';
import { getChallanById } from './challan.service';

export async function generateChallanPDF(challanId: string): Promise<Buffer> {
  const challan = await getChallanById(challanId);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40, size: 'A4' });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', (err: Error) => reject(err));

    // ─── Header ─────────────────────────────────────────────────────────────
    doc
      .fontSize(20)
      .fillColor('#1e293b')
      .text('DELIVERY CHALLAN / INVOICE', { align: 'center' });

    doc.moveDown(0.5);
    doc
      .fontSize(10)
      .fillColor('#64748b')
      .text('Mini ERP + CRM Operations Portal — Wholesale & Distribution', { align: 'center' });

    doc.moveDown(1);
    doc.strokeColor('#cbd5e1').lineWidth(1).moveTo(40, doc.y).lineTo(555, doc.y).stroke();
    doc.moveDown(1);

    // ─── Metadata Section (2-Column Grid) ───────────────────────────────────
    const metaTop = doc.y;

    // Left Column: Customer Info
    doc
      .fontSize(11)
      .fillColor('#0f172a')
      .text('Customer Details:', 40, metaTop)
      .fontSize(10)
      .fillColor('#334155')
      .text(`Business Name: ${challan.customer.businessName}`, 40, metaTop + 16)
      .text(`Contact Person: ${challan.customer.customerName}`, 40, metaTop + 30)
      .text(`Mobile: ${challan.customer.mobile}`, 40, metaTop + 44);

    // Right Column: Challan Metadata
    doc
      .fontSize(11)
      .fillColor('#0f172a')
      .text('Challan Details:', 320, metaTop)
      .fontSize(10)
      .fillColor('#334155')
      .text(`Challan No: ${challan.challanNumber}`, 320, metaTop + 16)
      .text(`Date: ${new Date(challan.createdAt).toLocaleDateString()}`, 320, metaTop + 30)
      .text(`Status: ${challan.status}`, 320, metaTop + 44)
      .text(`Generated By: ${challan.createdBy.name}`, 320, metaTop + 58);

    doc.y = metaTop + 85;
    doc.strokeColor('#cbd5e1').lineWidth(1).moveTo(40, doc.y).lineTo(555, doc.y).stroke();
    doc.moveDown(1);

    // ─── Table Headers ──────────────────────────────────────────────────────
    const tableTop = doc.y;
    doc.rect(40, tableTop, 515, 22).fill('#f1f5f9');

    doc
      .fontSize(9)
      .fillColor('#1e293b')
      .text('#', 48, tableTop + 6)
      .text('SKU', 75, tableTop + 6)
      .text('Product Name', 160, tableTop + 6)
      .text('Unit Price', 340, tableTop + 6, { width: 60, align: 'right' })
      .text('Quantity', 415, tableTop + 6, { width: 50, align: 'right' })
      .text('Total (INR)', 480, tableTop + 6, { width: 65, align: 'right' });

    let currentY = tableTop + 26;
    let grandTotal = 0;

    // ─── Line Items ─────────────────────────────────────────────────────────
    challan.items.forEach((item, index) => {
      const lineTotal = item.unitPrice * item.quantity;
      grandTotal += lineTotal;

      // Background alternating row
      if (index % 2 === 1) {
        doc.rect(40, currentY - 2, 515, 20).fill('#f8fafc');
      }

      doc
        .fontSize(9)
        .fillColor('#334155')
        .text(String(index + 1), 48, currentY + 3)
        .text(item.sku, 75, currentY + 3)
        .text(item.productName, 160, currentY + 3, { width: 175, ellipsis: true })
        .text(item.unitPrice.toFixed(2), 340, currentY + 3, { width: 60, align: 'right' })
        .text(String(item.quantity), 415, currentY + 3, { width: 50, align: 'right' })
        .text(lineTotal.toFixed(2), 480, currentY + 3, { width: 65, align: 'right' });

      currentY += 22;
    });

    doc.y = currentY + 5;
    doc.strokeColor('#cbd5e1').lineWidth(1).moveTo(40, doc.y).lineTo(555, doc.y).stroke();
    doc.moveDown(0.8);

    // ─── Summary Totals ─────────────────────────────────────────────────────
    const totalsY = doc.y;
    doc
      .fontSize(10)
      .fillColor('#0f172a')
      .text(`Total Line Items: ${challan.items.length}`, 48, totalsY)
      .text(`Total Quantity: ${challan.totalQuantity}`, 48, totalsY + 16)
      .fontSize(12)
      .text(`Grand Total: INR ${grandTotal.toFixed(2)}`, 340, totalsY + 6, {
        width: 205,
        align: 'right',
      });

    // ─── Footer / Signatures ────────────────────────────────────────────────
    const footerTop = 720;
    doc.strokeColor('#cbd5e1').lineWidth(1).moveTo(40, footerTop).lineTo(555, footerTop).stroke();

    doc
      .fontSize(9)
      .fillColor('#64748b')
      .text('Receiver Signature: _______________________', 48, footerTop + 20)
      .text('Authorized Signatory: _______________________', 340, footerTop + 20, {
        align: 'right',
        width: 205,
      });

    doc
      .fontSize(8)
      .fillColor('#94a3b8')
      .text('This is a computer-generated delivery challan from Mini ERP-CRM Operations Portal.', 40, footerTop + 55, {
        align: 'center',
      });

    doc.end();
  });
}

